spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fcbarca1899
    url: jdbc:mysql://127.0.0.1:3306/ems?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
server:
  port: 8085
